<?php


/**
 * Implements hook_field_formatter_info().
 */
function entity_field_reference_field_formatter_info() {
  return array(
    'entity_field_reference' => array(
      'label' => t('Entity field reference'),
      'description' => t('Display the selected field of the entity.'),
      'field types' => array('entityreference'),
      'settings' => array(
        'field' => FALSE,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function entity_field_reference_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  if ($display['type'] == 'entity_field_reference') {
    $entity_type = !empty($field['settings']['target_type']) ? $field['settings']['target_type'] : NULL;
    $entity_bundles = !empty($field['settings']['handler_settings']['target_bundles']) ? $field['settings']['handler_settings']['target_bundles'] : $entity_type;
    $fields = array();
    if (!empty($entity_bundles)) {
      if (is_array($entity_bundles)) {
        foreach ($entity_bundles as $entity_bundle) {
          $f = field_info_instances($entity_type, $entity_bundle);
          $fields = $fields + $f;
        }
      }
      else {
        $fields = field_info_instances($entity_type, $entity_bundles);
      }
    }

    $options = array();
    if (!empty($fields)) {
      foreach ($fields as $field_key => $field_value) {
        if ($field_key != $field['field_name']) {
          $options[$field_key] = $field_value['label'];
        }
      }
    }
    $element['field'] = array(
      '#title' => t('Link label to the referenced entity'),
      '#type' => 'select',
      '#options' => $options,
      '#default_value' => $settings['field'],
    );
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function entity_field_reference_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();
  if ($display['type'] == 'entity_field_reference') {
    $summary[] = $settings['field'] ? $settings['field'] : t('Default field');
  }
  return implode('<br />', $summary);
}


/**
 * Implements hook_field_formatter_view().
 */
function entity_field_reference_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $result = array();
  $settings = $display['settings'];
  switch ($display['type']) {
    case 'entity_field_reference':
      $field_name = $field['field_name'];
      if (!empty($entity->{$field_name})) {
        $target_type = $field['settings']['target_type'];
        foreach ($items as $delta => $item) {
          $ids[] = $item['target_id'];
        }
        $target_entities = entity_load($target_type, $ids);
        foreach ($target_entities as $target_entity) {
          if(!empty($target_entity->{$settings['field']})) {
            $output =  render(field_view_field($target_type, $target_entity, $settings['field'], array(), $langcode));
            $result[$delta] = array('#markup' => $output);
          }
        }
      }
      break;
  }
  return $result;
}